version: '3.8'

services:
  lexik_translation:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lexik_translation_test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
